### ISSUE TITLE
ValueError: too many values to unpack (expected 4) when runing test code with jaad

### ISSUE THREAD

**Issue by theekshana1987** [vita-epfl/bounding-box-prediction#20]
Traceback (most recent call last):
  File "test.py", line 301, in <module>
    test_3d(args, net, test_loader)
  File "test.py", line 217, in test_3d
    (obs_s, target_s, obs_p, target_p) = values
ValueError: too many values to unpack (expected 4)

**Comment by theekshana1987** [comment]
python3 preprocess/jaad_preprocessor.py --data_dir=/path/to/JAAD --train_ratio=0.7 --val_ratio=0.2 --test_ratio=0.1 this one with 
--input=16 --output=16 --stride=16
