### ISSUE TITLE
Can't pickle <class '__main__.args'>: it's not the same object as __main__.args

### ISSUE THREAD

**Issue by sunyuan789** [vita-epfl/bounding-box-prediction#8]
Sorry sir, there are some problems when I run your code. 
```python
Traceback (most recent call last):
  File "D:\anaconda\envs\open\lib\site-packages\IPython\core\interactiveshell.py", line 3524, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-5-9a191744a90c>", line 1, in <module>
    for idx, (obs_s, target_s, obs_p, target_p, target_c, label_c) in enumerate(train):
  File "D:\anaconda\envs\open\lib\site-packages\torch\utils\data\dataloader.py", line 368, in __iter__
    return self._get_iterator()
  File "D:\anaconda\envs\open\lib\site-packages\torch\utils\data\dataloader.py", line 314, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "D:\anaconda\envs\open\lib\site-packages\torch\utils\data\dataloader.py", line 927, in __init__
    w.start()
  File "D:\anaconda\envs\open\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "D:\anaconda\envs\open\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "D:\anaconda\envs\open\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "D:\anaconda\envs\open\lib\multiprocessing\popen_spawn_win32.py", line 89, in __init__
    reduction.dump(process_obj, to_child)
  File "D:\anaconda\envs\open\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <class '__main__.args'>: it's not the same object as __main__.args
```
I don't know how to solve it. Could you help me to solve it? Thank you!

**Comment by SaeedSaadatnejad** [comment]
Hello,

In which step, do you receive this error? Have you correctly installed the requirements?
